### ISSUE TITLE
Renaming of Runner

### ISSUE THREAD

**Issue by jberrytech** [near/workspaces#2]
Choose a new name for runner and associated repos

**Comment by chadoh** [comment]
[Gdoc with justification & discussion](https://docs.google.com/document/d/1_OzUtGX-sbzsSv4xGukdFjQBy_m45-qffPZsLyVWYqQ/edit?usp=sharing)

**Comment by volovyks** [comment]
Rust one is good. We need to rename some variables in the JS version.

**Comment by volovyks** [comment]
JS version renaming: https://github.com/near/workspaces-js/pull/96
